name: CI

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
          KEY_PROP: ${{ secrets.KEY_PROP }}
          run: echo $KEY_JKS > key.jks && echo $KEY_PROP > key.properties && flutter pub get && flutter test && flutter build apk --release
      - uses: actions/upload-artifact@v2
        with:
          name: release-x86_64
          path: build/app/outputs/apk/release/app-x86_64-release.apk
      - uses: actions/upload-artifact@v2
        with:
          name: release-arm64-v8a
          path: build/app/outputs/apk/release/app-arm64-v8a-release.apk
      - uses: actions/upload-artifact@v2
        with:
          name: release-armeabi-v7a
          path: build/app/outputs/apk/release/app-armeabi-v7a-release.apk
