name: CI

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: echo $KEY_JKS | base64 -di > android/key.jks
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PATH: ../key.jks
      - uses: actions/upload-artifact@v2
        with:
          name: release-x86_64
          path: build/app/outputs/apk/release/app-x86_64-release.apk
      - uses: actions/upload-artifact@v2
        with:
          name: release-arm64-v8a
          path: build/app/outputs/apk/release/app-arm64-v8a-release.apk
      - uses: actions/upload-artifact@v2
        with:
          name: release-armeabi-v7a
          path: build/app/outputs/apk/release/app-armeabi-v7a-release.apk
