name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: subosito/flutter-action@v1.4.0
      - uses: actions/checkout@v2
        
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
