name: CI/CD

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: echo $KEY_JKS | base64 -di > android/key.jks
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PATH: ../key.jks
      - uses: actions/upload-artifact@v2
        with:
          name: folio-x86_64
          path: build/app/outputs/apk/release/app-x86_64-release.apk
      - uses: actions/upload-artifact@v2
        with:
          name: folio-arm64-v8a
          path: build/app/outputs/apk/release/app-arm64-v8a-release.apk
      - uses: actions/upload-artifact@v2
        with:
          name: folio-armeabi-v7a
          path: build/app/outputs/apk/release/app-armeabi-v7a-release.apk


  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Download APKs
        uses: actions/download-artifact@v2
      - name: Upload arm64-v8a APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./folio-arm64-v8a/app-arm64-v8a-release.apk
          asset_name: folio-arm64-v8a.apk
          asset_content_type: application/octet-stream
      - name: Upload armeabi-v7a APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./folio-armeabi-v7a/app-armeabi-v7a-release.apk
          asset_name: folio-armeabi-v7a.apk
          asset_content_type: application/octet-stream
      - name: Upload x86_64 APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./folio-x86_64/app-x86_64-release.apk
          asset_name: folio-x86_64.apk
          asset_content_type: application/octet-stream