/// Flutter icons Folio
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Folio
///      fonts:
///       - asset: fonts/Folio.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Folio {
  Folio._();

  static const _kFontFam = 'Folio';
  static const _kFontPkg = null;

  static const IconData pin = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unpin = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
